//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReferenceGameStore
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GameForView", Namespace="http://schemas.datacontract.org/2004/07/WcfGameStore.ViewModel")]
    public partial class GameForView : object
    {
        
        private string CodeField;
        
        private System.Nullable<System.DateTime> CreationDateField;
        
        private string FotoUrlField;
        
        private int GameIDField;
        
        private System.Nullable<System.DateTime> ModifiedDateField;
        
        private string NotesField;
        
        private System.Nullable<decimal> PriceField;
        
        private System.Nullable<decimal> QuantityField;
        
        private string ShortDescriptionField;
        
        private string StudioField;
        
        private string TitleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreationDate
        {
            get
            {
                return this.CreationDateField;
            }
            set
            {
                this.CreationDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FotoUrl
        {
            get
            {
                return this.FotoUrlField;
            }
            set
            {
                this.FotoUrlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GameID
        {
            get
            {
                return this.GameIDField;
            }
            set
            {
                this.GameIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ModifiedDate
        {
            get
            {
                return this.ModifiedDateField;
            }
            set
            {
                this.ModifiedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Notes
        {
            get
            {
                return this.NotesField;
            }
            set
            {
                this.NotesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Price
        {
            get
            {
                return this.PriceField;
            }
            set
            {
                this.PriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Quantity
        {
            get
            {
                return this.QuantityField;
            }
            set
            {
                this.QuantityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShortDescription
        {
            get
            {
                return this.ShortDescriptionField;
            }
            set
            {
                this.ShortDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Studio
        {
            get
            {
                return this.StudioField;
            }
            set
            {
                this.StudioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerForView", Namespace="http://schemas.datacontract.org/2004/07/WcfGameStore.ViewModel")]
    public partial class CustomerForView : object
    {
        
        private string CityField;
        
        private string CountryField;
        
        private int CustomerIDField;
        
        private string EmailField;
        
        private string HouseNumberField;
        
        private System.DateTime ModifiedDateField;
        
        private string NameField;
        
        private string PhoneField;
        
        private string PostCodeField;
        
        private string StreetField;
        
        private string SurnameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City
        {
            get
            {
                return this.CityField;
            }
            set
            {
                this.CityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country
        {
            get
            {
                return this.CountryField;
            }
            set
            {
                this.CountryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerID
        {
            get
            {
                return this.CustomerIDField;
            }
            set
            {
                this.CustomerIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HouseNumber
        {
            get
            {
                return this.HouseNumberField;
            }
            set
            {
                this.HouseNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ModifiedDate
        {
            get
            {
                return this.ModifiedDateField;
            }
            set
            {
                this.ModifiedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone
        {
            get
            {
                return this.PhoneField;
            }
            set
            {
                this.PhoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostCode
        {
            get
            {
                return this.PostCodeField;
            }
            set
            {
                this.PostCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Street
        {
            get
            {
                return this.StreetField;
            }
            set
            {
                this.StreetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Surname
        {
            get
            {
                return this.SurnameField;
            }
            set
            {
                this.SurnameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmployeeForView", Namespace="http://schemas.datacontract.org/2004/07/WcfGameStore.ViewModel")]
    public partial class EmployeeForView : object
    {
        
        private string DepartmentField;
        
        private string EmailField;
        
        private int EmployeeIDField;
        
        private string LoginField;
        
        private string NameField;
        
        private string PasswordField;
        
        private string PhoneField;
        
        private string SurnameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Department
        {
            get
            {
                return this.DepartmentField;
            }
            set
            {
                this.DepartmentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EmployeeID
        {
            get
            {
                return this.EmployeeIDField;
            }
            set
            {
                this.EmployeeIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login
        {
            get
            {
                return this.LoginField;
            }
            set
            {
                this.LoginField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone
        {
            get
            {
                return this.PhoneField;
            }
            set
            {
                this.PhoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Surname
        {
            get
            {
                return this.SurnameField;
            }
            set
            {
                this.SurnameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderForView", Namespace="http://schemas.datacontract.org/2004/07/WcfGameStore.ViewModel")]
    public partial class OrderForView : object
    {
        
        private System.Nullable<int> CustomerIDField;
        
        private System.Nullable<int> EmployeeIDField;
        
        private System.Nullable<System.DateTime> ModifiedDateField;
        
        private System.Nullable<System.DateTime> OrderDateField;
        
        private System.Collections.Generic.List<ServiceReferenceGameStore.OrderDetailForView> OrderDetailField;
        
        private int OrderIDField;
        
        private string OrderNumberField;
        
        private System.Nullable<int> PaymentMethodIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CustomerID
        {
            get
            {
                return this.CustomerIDField;
            }
            set
            {
                this.CustomerIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> EmployeeID
        {
            get
            {
                return this.EmployeeIDField;
            }
            set
            {
                this.EmployeeIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ModifiedDate
        {
            get
            {
                return this.ModifiedDateField;
            }
            set
            {
                this.ModifiedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> OrderDate
        {
            get
            {
                return this.OrderDateField;
            }
            set
            {
                this.OrderDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ServiceReferenceGameStore.OrderDetailForView> OrderDetail
        {
            get
            {
                return this.OrderDetailField;
            }
            set
            {
                this.OrderDetailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderID
        {
            get
            {
                return this.OrderIDField;
            }
            set
            {
                this.OrderIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderNumber
        {
            get
            {
                return this.OrderNumberField;
            }
            set
            {
                this.OrderNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PaymentMethodID
        {
            get
            {
                return this.PaymentMethodIDField;
            }
            set
            {
                this.PaymentMethodIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderDetailForView", Namespace="http://schemas.datacontract.org/2004/07/WcfGameStore.ViewModel")]
    public partial class OrderDetailForView : object
    {
        
        private System.Nullable<decimal> DiscountField;
        
        private int GameIDField;
        
        private System.Nullable<decimal> GrossPriceField;
        
        private System.Nullable<System.DateTime> ModifiedDateField;
        
        private System.Nullable<decimal> NetPriceField;
        
        private int OrderIDField;
        
        private System.Nullable<int> QuantityField;
        
        private System.Nullable<decimal> TaxField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Discount
        {
            get
            {
                return this.DiscountField;
            }
            set
            {
                this.DiscountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GameID
        {
            get
            {
                return this.GameIDField;
            }
            set
            {
                this.GameIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> GrossPrice
        {
            get
            {
                return this.GrossPriceField;
            }
            set
            {
                this.GrossPriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ModifiedDate
        {
            get
            {
                return this.ModifiedDateField;
            }
            set
            {
                this.ModifiedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> NetPrice
        {
            get
            {
                return this.NetPriceField;
            }
            set
            {
                this.NetPriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderID
        {
            get
            {
                return this.OrderIDField;
            }
            set
            {
                this.OrderIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Quantity
        {
            get
            {
                return this.QuantityField;
            }
            set
            {
                this.QuantityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Tax
        {
            get
            {
                return this.TaxField;
            }
            set
            {
                this.TaxField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CategoryForView", Namespace="http://schemas.datacontract.org/2004/07/WcfGameStore.ViewModel")]
    public partial class CategoryForView : object
    {
        
        private int CategoryIDField;
        
        private System.Nullable<System.DateTime> ModifiedDateField;
        
        private string NameField;
        
        private string NotesField;
        
        private string ShortDescriptionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CategoryID
        {
            get
            {
                return this.CategoryIDField;
            }
            set
            {
                this.CategoryIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ModifiedDate
        {
            get
            {
                return this.ModifiedDateField;
            }
            set
            {
                this.ModifiedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Notes
        {
            get
            {
                return this.NotesField;
            }
            set
            {
                this.NotesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShortDescription
        {
            get
            {
                return this.ShortDescriptionField;
            }
            set
            {
                this.ShortDescriptionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GameTypeForView", Namespace="http://schemas.datacontract.org/2004/07/WcfGameStore.ViewModel")]
    public partial class GameTypeForView : object
    {
        
        private int CategoryIDField;
        
        private int GameIDField;
        
        private System.Nullable<System.DateTime> ModifiedDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CategoryID
        {
            get
            {
                return this.CategoryIDField;
            }
            set
            {
                this.CategoryIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GameID
        {
            get
            {
                return this.GameIDField;
            }
            set
            {
                this.GameIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ModifiedDate
        {
            get
            {
                return this.ModifiedDateField;
            }
            set
            {
                this.ModifiedDateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentMethodForView", Namespace="http://schemas.datacontract.org/2004/07/WcfGameStore.ViewModel")]
    public partial class PaymentMethodForView : object
    {
        
        private bool IsActiveField;
        
        private System.Nullable<System.DateTime> ModifiedDateField;
        
        private string NameField;
        
        private string NotesField;
        
        private int PaymentMethodIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsActive
        {
            get
            {
                return this.IsActiveField;
            }
            set
            {
                this.IsActiveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ModifiedDate
        {
            get
            {
                return this.ModifiedDateField;
            }
            set
            {
                this.ModifiedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Notes
        {
            get
            {
                return this.NotesField;
            }
            set
            {
                this.NotesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PaymentMethodID
        {
            get
            {
                return this.PaymentMethodIDField;
            }
            set
            {
                this.PaymentMethodIDField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceGameStore.IGameStoreService")]
    public interface IGameStoreService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameStoreService/GetGames", ReplyAction="http://tempuri.org/IGameStoreService/GetGamesResponse")]
        ServiceReferenceGameStore.GetGamesResponse GetGames(ServiceReferenceGameStore.GetGamesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameStoreService/GetGames", ReplyAction="http://tempuri.org/IGameStoreService/GetGamesResponse")]
        System.Threading.Tasks.Task<ServiceReferenceGameStore.GetGamesResponse> GetGamesAsync(ServiceReferenceGameStore.GetGamesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameStoreService/GetGameSortByName", ReplyAction="http://tempuri.org/IGameStoreService/GetGameSortByNameResponse")]
        ServiceReferenceGameStore.GetGameSortByNameResponse GetGameSortByName(ServiceReferenceGameStore.GetGameSortByNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameStoreService/GetGameSortByName", ReplyAction="http://tempuri.org/IGameStoreService/GetGameSortByNameResponse")]
        System.Threading.Tasks.Task<ServiceReferenceGameStore.GetGameSortByNameResponse> GetGameSortByNameAsync(ServiceReferenceGameStore.GetGameSortByNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameStoreService/AddOrUpdateGame", ReplyAction="http://tempuri.org/IGameStoreService/AddOrUpdateGameResponse")]
        ServiceReferenceGameStore.AddOrUpdateGameResponse AddOrUpdateGame(ServiceReferenceGameStore.AddOrUpdateGameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameStoreService/AddOrUpdateGame", ReplyAction="http://tempuri.org/IGameStoreService/AddOrUpdateGameResponse")]
        System.Threading.Tasks.Task<ServiceReferenceGameStore.AddOrUpdateGameResponse> AddOrUpdateGameAsync(ServiceReferenceGameStore.AddOrUpdateGameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameStoreService/GetCustomers", ReplyAction="http://tempuri.org/IGameStoreService/GetCustomersResponse")]
        ServiceReferenceGameStore.GetCustomersResponse GetCustomers(ServiceReferenceGameStore.GetCustomersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameStoreService/GetCustomers", ReplyAction="http://tempuri.org/IGameStoreService/GetCustomersResponse")]
        System.Threading.Tasks.Task<ServiceReferenceGameStore.GetCustomersResponse> GetCustomersAsync(ServiceReferenceGameStore.GetCustomersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameStoreService/GetCustomerSortByName", ReplyAction="http://tempuri.org/IGameStoreService/GetCustomerSortByNameResponse")]
        ServiceReferenceGameStore.GetCustomerSortByNameResponse GetCustomerSortByName(ServiceReferenceGameStore.GetCustomerSortByNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameStoreService/GetCustomerSortByName", ReplyAction="http://tempuri.org/IGameStoreService/GetCustomerSortByNameResponse")]
        System.Threading.Tasks.Task<ServiceReferenceGameStore.GetCustomerSortByNameResponse> GetCustomerSortByNameAsync(ServiceReferenceGameStore.GetCustomerSortByNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameStoreService/AddOrUpdateCustomer", ReplyAction="http://tempuri.org/IGameStoreService/AddOrUpdateCustomerResponse")]
        ServiceReferenceGameStore.AddOrUpdateCustomerResponse AddOrUpdateCustomer(ServiceReferenceGameStore.AddOrUpdateCustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameStoreService/AddOrUpdateCustomer", ReplyAction="http://tempuri.org/IGameStoreService/AddOrUpdateCustomerResponse")]
        System.Threading.Tasks.Task<ServiceReferenceGameStore.AddOrUpdateCustomerResponse> AddOrUpdateCustomerAsync(ServiceReferenceGameStore.AddOrUpdateCustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameStoreService/AddOrUpdateEmployee", ReplyAction="http://tempuri.org/IGameStoreService/AddOrUpdateEmployeeResponse")]
        ServiceReferenceGameStore.AddOrUpdateEmployeeResponse AddOrUpdateEmployee(ServiceReferenceGameStore.AddOrUpdateEmployeeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameStoreService/AddOrUpdateEmployee", ReplyAction="http://tempuri.org/IGameStoreService/AddOrUpdateEmployeeResponse")]
        System.Threading.Tasks.Task<ServiceReferenceGameStore.AddOrUpdateEmployeeResponse> AddOrUpdateEmployeeAsync(ServiceReferenceGameStore.AddOrUpdateEmployeeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameStoreService/GetEmployees", ReplyAction="http://tempuri.org/IGameStoreService/GetEmployeesResponse")]
        ServiceReferenceGameStore.GetEmployeesResponse GetEmployees(ServiceReferenceGameStore.GetEmployeesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameStoreService/GetEmployees", ReplyAction="http://tempuri.org/IGameStoreService/GetEmployeesResponse")]
        System.Threading.Tasks.Task<ServiceReferenceGameStore.GetEmployeesResponse> GetEmployeesAsync(ServiceReferenceGameStore.GetEmployeesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameStoreService/GetEmployeeSortByName", ReplyAction="http://tempuri.org/IGameStoreService/GetEmployeeSortByNameResponse")]
        ServiceReferenceGameStore.GetEmployeeSortByNameResponse GetEmployeeSortByName(ServiceReferenceGameStore.GetEmployeeSortByNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameStoreService/GetEmployeeSortByName", ReplyAction="http://tempuri.org/IGameStoreService/GetEmployeeSortByNameResponse")]
        System.Threading.Tasks.Task<ServiceReferenceGameStore.GetEmployeeSortByNameResponse> GetEmployeeSortByNameAsync(ServiceReferenceGameStore.GetEmployeeSortByNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameStoreService/GetOrders", ReplyAction="http://tempuri.org/IGameStoreService/GetOrdersResponse")]
        ServiceReferenceGameStore.GetOrdersResponse GetOrders(ServiceReferenceGameStore.GetOrdersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameStoreService/GetOrders", ReplyAction="http://tempuri.org/IGameStoreService/GetOrdersResponse")]
        System.Threading.Tasks.Task<ServiceReferenceGameStore.GetOrdersResponse> GetOrdersAsync(ServiceReferenceGameStore.GetOrdersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameStoreService/GetOrderSortByOrderNumber", ReplyAction="http://tempuri.org/IGameStoreService/GetOrderSortByOrderNumberResponse")]
        ServiceReferenceGameStore.GetOrderSortByOrderNumberResponse GetOrderSortByOrderNumber(ServiceReferenceGameStore.GetOrderSortByOrderNumberRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameStoreService/GetOrderSortByOrderNumber", ReplyAction="http://tempuri.org/IGameStoreService/GetOrderSortByOrderNumberResponse")]
        System.Threading.Tasks.Task<ServiceReferenceGameStore.GetOrderSortByOrderNumberResponse> GetOrderSortByOrderNumberAsync(ServiceReferenceGameStore.GetOrderSortByOrderNumberRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameStoreService/AddOrUpdateOrder", ReplyAction="http://tempuri.org/IGameStoreService/AddOrUpdateOrderResponse")]
        ServiceReferenceGameStore.AddOrUpdateOrderResponse AddOrUpdateOrder(ServiceReferenceGameStore.AddOrUpdateOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameStoreService/AddOrUpdateOrder", ReplyAction="http://tempuri.org/IGameStoreService/AddOrUpdateOrderResponse")]
        System.Threading.Tasks.Task<ServiceReferenceGameStore.AddOrUpdateOrderResponse> AddOrUpdateOrderAsync(ServiceReferenceGameStore.AddOrUpdateOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameStoreService/GetCategories", ReplyAction="http://tempuri.org/IGameStoreService/GetCategoriesResponse")]
        ServiceReferenceGameStore.GetCategoriesResponse GetCategories(ServiceReferenceGameStore.GetCategoriesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameStoreService/GetCategories", ReplyAction="http://tempuri.org/IGameStoreService/GetCategoriesResponse")]
        System.Threading.Tasks.Task<ServiceReferenceGameStore.GetCategoriesResponse> GetCategoriesAsync(ServiceReferenceGameStore.GetCategoriesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameStoreService/GetCategorySortByName", ReplyAction="http://tempuri.org/IGameStoreService/GetCategorySortByNameResponse")]
        ServiceReferenceGameStore.GetCategorySortByNameResponse GetCategorySortByName(ServiceReferenceGameStore.GetCategorySortByNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameStoreService/GetCategorySortByName", ReplyAction="http://tempuri.org/IGameStoreService/GetCategorySortByNameResponse")]
        System.Threading.Tasks.Task<ServiceReferenceGameStore.GetCategorySortByNameResponse> GetCategorySortByNameAsync(ServiceReferenceGameStore.GetCategorySortByNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameStoreService/AddOrUpdateCategory", ReplyAction="http://tempuri.org/IGameStoreService/AddOrUpdateCategoryResponse")]
        ServiceReferenceGameStore.AddOrUpdateCategoryResponse AddOrUpdateCategory(ServiceReferenceGameStore.AddOrUpdateCategoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameStoreService/AddOrUpdateCategory", ReplyAction="http://tempuri.org/IGameStoreService/AddOrUpdateCategoryResponse")]
        System.Threading.Tasks.Task<ServiceReferenceGameStore.AddOrUpdateCategoryResponse> AddOrUpdateCategoryAsync(ServiceReferenceGameStore.AddOrUpdateCategoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameStoreService/GetGameTypes", ReplyAction="http://tempuri.org/IGameStoreService/GetGameTypesResponse")]
        ServiceReferenceGameStore.GetGameTypesResponse GetGameTypes(ServiceReferenceGameStore.GetGameTypesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameStoreService/GetGameTypes", ReplyAction="http://tempuri.org/IGameStoreService/GetGameTypesResponse")]
        System.Threading.Tasks.Task<ServiceReferenceGameStore.GetGameTypesResponse> GetGameTypesAsync(ServiceReferenceGameStore.GetGameTypesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameStoreService/AddOrUpdateGameType", ReplyAction="http://tempuri.org/IGameStoreService/AddOrUpdateGameTypeResponse")]
        ServiceReferenceGameStore.AddOrUpdateGameTypeResponse AddOrUpdateGameType(ServiceReferenceGameStore.AddOrUpdateGameTypeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameStoreService/AddOrUpdateGameType", ReplyAction="http://tempuri.org/IGameStoreService/AddOrUpdateGameTypeResponse")]
        System.Threading.Tasks.Task<ServiceReferenceGameStore.AddOrUpdateGameTypeResponse> AddOrUpdateGameTypeAsync(ServiceReferenceGameStore.AddOrUpdateGameTypeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameStoreService/GetPaymentMethods", ReplyAction="http://tempuri.org/IGameStoreService/GetPaymentMethodsResponse")]
        ServiceReferenceGameStore.GetPaymentMethodsResponse GetPaymentMethods(ServiceReferenceGameStore.GetPaymentMethodsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameStoreService/GetPaymentMethods", ReplyAction="http://tempuri.org/IGameStoreService/GetPaymentMethodsResponse")]
        System.Threading.Tasks.Task<ServiceReferenceGameStore.GetPaymentMethodsResponse> GetPaymentMethodsAsync(ServiceReferenceGameStore.GetPaymentMethodsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameStoreService/AddOrUpdatePaymentMethod", ReplyAction="http://tempuri.org/IGameStoreService/AddOrUpdatePaymentMethodResponse")]
        ServiceReferenceGameStore.AddOrUpdatePaymentMethodResponse AddOrUpdatePaymentMethod(ServiceReferenceGameStore.AddOrUpdatePaymentMethodRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameStoreService/AddOrUpdatePaymentMethod", ReplyAction="http://tempuri.org/IGameStoreService/AddOrUpdatePaymentMethodResponse")]
        System.Threading.Tasks.Task<ServiceReferenceGameStore.AddOrUpdatePaymentMethodResponse> AddOrUpdatePaymentMethodAsync(ServiceReferenceGameStore.AddOrUpdatePaymentMethodRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameStoreService/GetOrderDetail", ReplyAction="http://tempuri.org/IGameStoreService/GetOrderDetailResponse")]
        ServiceReferenceGameStore.GetOrderDetailResponse GetOrderDetail(ServiceReferenceGameStore.GetOrderDetailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameStoreService/GetOrderDetail", ReplyAction="http://tempuri.org/IGameStoreService/GetOrderDetailResponse")]
        System.Threading.Tasks.Task<ServiceReferenceGameStore.GetOrderDetailResponse> GetOrderDetailAsync(ServiceReferenceGameStore.GetOrderDetailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameStoreService/SalesReportForGame", ReplyAction="http://tempuri.org/IGameStoreService/SalesReportForGameResponse")]
        ServiceReferenceGameStore.SalesReportForGameResponse SalesReportForGame(ServiceReferenceGameStore.SalesReportForGameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameStoreService/SalesReportForGame", ReplyAction="http://tempuri.org/IGameStoreService/SalesReportForGameResponse")]
        System.Threading.Tasks.Task<ServiceReferenceGameStore.SalesReportForGameResponse> SalesReportForGameAsync(ServiceReferenceGameStore.SalesReportForGameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameStoreService/OrderValueOfWorker", ReplyAction="http://tempuri.org/IGameStoreService/OrderValueOfWorkerResponse")]
        ServiceReferenceGameStore.OrderValueOfWorkerResponse OrderValueOfWorker(ServiceReferenceGameStore.OrderValueOfWorkerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameStoreService/OrderValueOfWorker", ReplyAction="http://tempuri.org/IGameStoreService/OrderValueOfWorkerResponse")]
        System.Threading.Tasks.Task<ServiceReferenceGameStore.OrderValueOfWorkerResponse> OrderValueOfWorkerAsync(ServiceReferenceGameStore.OrderValueOfWorkerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameStoreService/SalesReport", ReplyAction="http://tempuri.org/IGameStoreService/SalesReportResponse")]
        ServiceReferenceGameStore.SalesReportResponse SalesReport(ServiceReferenceGameStore.SalesReportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameStoreService/SalesReport", ReplyAction="http://tempuri.org/IGameStoreService/SalesReportResponse")]
        System.Threading.Tasks.Task<ServiceReferenceGameStore.SalesReportResponse> SalesReportAsync(ServiceReferenceGameStore.SalesReportRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetGames", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetGamesRequest
    {
        
        public GetGamesRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetGamesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetGamesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<ServiceReferenceGameStore.GameForView> GetGamesResult;
        
        public GetGamesResponse()
        {
        }
        
        public GetGamesResponse(System.Collections.Generic.List<ServiceReferenceGameStore.GameForView> GetGamesResult)
        {
            this.GetGamesResult = GetGamesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetGameSortByName", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetGameSortByNameRequest
    {
        
        public GetGameSortByNameRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetGameSortByNameResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetGameSortByNameResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<ServiceReferenceGameStore.GameForView> GetGameSortByNameResult;
        
        public GetGameSortByNameResponse()
        {
        }
        
        public GetGameSortByNameResponse(System.Collections.Generic.List<ServiceReferenceGameStore.GameForView> GetGameSortByNameResult)
        {
            this.GetGameSortByNameResult = GetGameSortByNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddOrUpdateGame", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddOrUpdateGameRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServiceReferenceGameStore.GameForView game;
        
        public AddOrUpdateGameRequest()
        {
        }
        
        public AddOrUpdateGameRequest(ServiceReferenceGameStore.GameForView game)
        {
            this.game = game;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddOrUpdateGameResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddOrUpdateGameResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool AddOrUpdateGameResult;
        
        public AddOrUpdateGameResponse()
        {
        }
        
        public AddOrUpdateGameResponse(bool AddOrUpdateGameResult)
        {
            this.AddOrUpdateGameResult = AddOrUpdateGameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCustomers", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCustomersRequest
    {
        
        public GetCustomersRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCustomersResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCustomersResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<ServiceReferenceGameStore.CustomerForView> GetCustomersResult;
        
        public GetCustomersResponse()
        {
        }
        
        public GetCustomersResponse(System.Collections.Generic.List<ServiceReferenceGameStore.CustomerForView> GetCustomersResult)
        {
            this.GetCustomersResult = GetCustomersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCustomerSortByName", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCustomerSortByNameRequest
    {
        
        public GetCustomerSortByNameRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCustomerSortByNameResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCustomerSortByNameResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<ServiceReferenceGameStore.CustomerForView> GetCustomerSortByNameResult;
        
        public GetCustomerSortByNameResponse()
        {
        }
        
        public GetCustomerSortByNameResponse(System.Collections.Generic.List<ServiceReferenceGameStore.CustomerForView> GetCustomerSortByNameResult)
        {
            this.GetCustomerSortByNameResult = GetCustomerSortByNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddOrUpdateCustomer", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddOrUpdateCustomerRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServiceReferenceGameStore.CustomerForView customer;
        
        public AddOrUpdateCustomerRequest()
        {
        }
        
        public AddOrUpdateCustomerRequest(ServiceReferenceGameStore.CustomerForView customer)
        {
            this.customer = customer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddOrUpdateCustomerResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddOrUpdateCustomerResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool AddOrUpdateCustomerResult;
        
        public AddOrUpdateCustomerResponse()
        {
        }
        
        public AddOrUpdateCustomerResponse(bool AddOrUpdateCustomerResult)
        {
            this.AddOrUpdateCustomerResult = AddOrUpdateCustomerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddOrUpdateEmployee", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddOrUpdateEmployeeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServiceReferenceGameStore.EmployeeForView employee;
        
        public AddOrUpdateEmployeeRequest()
        {
        }
        
        public AddOrUpdateEmployeeRequest(ServiceReferenceGameStore.EmployeeForView employee)
        {
            this.employee = employee;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddOrUpdateEmployeeResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddOrUpdateEmployeeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool AddOrUpdateEmployeeResult;
        
        public AddOrUpdateEmployeeResponse()
        {
        }
        
        public AddOrUpdateEmployeeResponse(bool AddOrUpdateEmployeeResult)
        {
            this.AddOrUpdateEmployeeResult = AddOrUpdateEmployeeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetEmployees", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetEmployeesRequest
    {
        
        public GetEmployeesRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetEmployeesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetEmployeesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<ServiceReferenceGameStore.EmployeeForView> GetEmployeesResult;
        
        public GetEmployeesResponse()
        {
        }
        
        public GetEmployeesResponse(System.Collections.Generic.List<ServiceReferenceGameStore.EmployeeForView> GetEmployeesResult)
        {
            this.GetEmployeesResult = GetEmployeesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetEmployeeSortByName", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetEmployeeSortByNameRequest
    {
        
        public GetEmployeeSortByNameRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetEmployeeSortByNameResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetEmployeeSortByNameResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<ServiceReferenceGameStore.EmployeeForView> GetEmployeeSortByNameResult;
        
        public GetEmployeeSortByNameResponse()
        {
        }
        
        public GetEmployeeSortByNameResponse(System.Collections.Generic.List<ServiceReferenceGameStore.EmployeeForView> GetEmployeeSortByNameResult)
        {
            this.GetEmployeeSortByNameResult = GetEmployeeSortByNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetOrders", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetOrdersRequest
    {
        
        public GetOrdersRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetOrdersResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetOrdersResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<ServiceReferenceGameStore.OrderForView> GetOrdersResult;
        
        public GetOrdersResponse()
        {
        }
        
        public GetOrdersResponse(System.Collections.Generic.List<ServiceReferenceGameStore.OrderForView> GetOrdersResult)
        {
            this.GetOrdersResult = GetOrdersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetOrderSortByOrderNumber", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetOrderSortByOrderNumberRequest
    {
        
        public GetOrderSortByOrderNumberRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetOrderSortByOrderNumberResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetOrderSortByOrderNumberResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<ServiceReferenceGameStore.OrderForView> GetOrderSortByOrderNumberResult;
        
        public GetOrderSortByOrderNumberResponse()
        {
        }
        
        public GetOrderSortByOrderNumberResponse(System.Collections.Generic.List<ServiceReferenceGameStore.OrderForView> GetOrderSortByOrderNumberResult)
        {
            this.GetOrderSortByOrderNumberResult = GetOrderSortByOrderNumberResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddOrUpdateOrder", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddOrUpdateOrderRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServiceReferenceGameStore.OrderForView order;
        
        public AddOrUpdateOrderRequest()
        {
        }
        
        public AddOrUpdateOrderRequest(ServiceReferenceGameStore.OrderForView order)
        {
            this.order = order;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddOrUpdateOrderResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddOrUpdateOrderResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool AddOrUpdateOrderResult;
        
        public AddOrUpdateOrderResponse()
        {
        }
        
        public AddOrUpdateOrderResponse(bool AddOrUpdateOrderResult)
        {
            this.AddOrUpdateOrderResult = AddOrUpdateOrderResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCategories", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCategoriesRequest
    {
        
        public GetCategoriesRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCategoriesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCategoriesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<ServiceReferenceGameStore.CategoryForView> GetCategoriesResult;
        
        public GetCategoriesResponse()
        {
        }
        
        public GetCategoriesResponse(System.Collections.Generic.List<ServiceReferenceGameStore.CategoryForView> GetCategoriesResult)
        {
            this.GetCategoriesResult = GetCategoriesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCategorySortByName", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCategorySortByNameRequest
    {
        
        public GetCategorySortByNameRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCategorySortByNameResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCategorySortByNameResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<ServiceReferenceGameStore.CategoryForView> GetCategorySortByNameResult;
        
        public GetCategorySortByNameResponse()
        {
        }
        
        public GetCategorySortByNameResponse(System.Collections.Generic.List<ServiceReferenceGameStore.CategoryForView> GetCategorySortByNameResult)
        {
            this.GetCategorySortByNameResult = GetCategorySortByNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddOrUpdateCategory", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddOrUpdateCategoryRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServiceReferenceGameStore.CategoryForView category;
        
        public AddOrUpdateCategoryRequest()
        {
        }
        
        public AddOrUpdateCategoryRequest(ServiceReferenceGameStore.CategoryForView category)
        {
            this.category = category;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddOrUpdateCategoryResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddOrUpdateCategoryResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool AddOrUpdateCategoryResult;
        
        public AddOrUpdateCategoryResponse()
        {
        }
        
        public AddOrUpdateCategoryResponse(bool AddOrUpdateCategoryResult)
        {
            this.AddOrUpdateCategoryResult = AddOrUpdateCategoryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetGameTypes", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetGameTypesRequest
    {
        
        public GetGameTypesRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetGameTypesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetGameTypesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<ServiceReferenceGameStore.GameTypeForView> GetGameTypesResult;
        
        public GetGameTypesResponse()
        {
        }
        
        public GetGameTypesResponse(System.Collections.Generic.List<ServiceReferenceGameStore.GameTypeForView> GetGameTypesResult)
        {
            this.GetGameTypesResult = GetGameTypesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddOrUpdateGameType", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddOrUpdateGameTypeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServiceReferenceGameStore.GameTypeForView gameType;
        
        public AddOrUpdateGameTypeRequest()
        {
        }
        
        public AddOrUpdateGameTypeRequest(ServiceReferenceGameStore.GameTypeForView gameType)
        {
            this.gameType = gameType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddOrUpdateGameTypeResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddOrUpdateGameTypeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool AddOrUpdateGameTypeResult;
        
        public AddOrUpdateGameTypeResponse()
        {
        }
        
        public AddOrUpdateGameTypeResponse(bool AddOrUpdateGameTypeResult)
        {
            this.AddOrUpdateGameTypeResult = AddOrUpdateGameTypeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPaymentMethods", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetPaymentMethodsRequest
    {
        
        public GetPaymentMethodsRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPaymentMethodsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetPaymentMethodsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<ServiceReferenceGameStore.PaymentMethodForView> GetPaymentMethodsResult;
        
        public GetPaymentMethodsResponse()
        {
        }
        
        public GetPaymentMethodsResponse(System.Collections.Generic.List<ServiceReferenceGameStore.PaymentMethodForView> GetPaymentMethodsResult)
        {
            this.GetPaymentMethodsResult = GetPaymentMethodsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddOrUpdatePaymentMethod", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddOrUpdatePaymentMethodRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServiceReferenceGameStore.PaymentMethodForView paymentMethod;
        
        public AddOrUpdatePaymentMethodRequest()
        {
        }
        
        public AddOrUpdatePaymentMethodRequest(ServiceReferenceGameStore.PaymentMethodForView paymentMethod)
        {
            this.paymentMethod = paymentMethod;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddOrUpdatePaymentMethodResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddOrUpdatePaymentMethodResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool AddOrUpdatePaymentMethodResult;
        
        public AddOrUpdatePaymentMethodResponse()
        {
        }
        
        public AddOrUpdatePaymentMethodResponse(bool AddOrUpdatePaymentMethodResult)
        {
            this.AddOrUpdatePaymentMethodResult = AddOrUpdatePaymentMethodResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetOrderDetail", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetOrderDetailRequest
    {
        
        public GetOrderDetailRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetOrderDetailResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetOrderDetailResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<ServiceReferenceGameStore.OrderDetailForView> GetOrderDetailResult;
        
        public GetOrderDetailResponse()
        {
        }
        
        public GetOrderDetailResponse(System.Collections.Generic.List<ServiceReferenceGameStore.OrderDetailForView> GetOrderDetailResult)
        {
            this.GetOrderDetailResult = GetOrderDetailResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SalesReportForGame", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SalesReportForGameRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.DateTime dateFrom;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.DateTime datoTo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int gameId;
        
        public SalesReportForGameRequest()
        {
        }
        
        public SalesReportForGameRequest(System.DateTime dateFrom, System.DateTime datoTo, int gameId)
        {
            this.dateFrom = dateFrom;
            this.datoTo = datoTo;
            this.gameId = gameId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SalesReportForGameResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SalesReportForGameResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Nullable<decimal> SalesReportForGameResult;
        
        public SalesReportForGameResponse()
        {
        }
        
        public SalesReportForGameResponse(System.Nullable<decimal> SalesReportForGameResult)
        {
            this.SalesReportForGameResult = SalesReportForGameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OrderValueOfWorker", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class OrderValueOfWorkerRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int employeeID;
        
        public OrderValueOfWorkerRequest()
        {
        }
        
        public OrderValueOfWorkerRequest(int employeeID)
        {
            this.employeeID = employeeID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OrderValueOfWorkerResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class OrderValueOfWorkerResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Nullable<decimal> OrderValueOfWorkerResult;
        
        public OrderValueOfWorkerResponse()
        {
        }
        
        public OrderValueOfWorkerResponse(System.Nullable<decimal> OrderValueOfWorkerResult)
        {
            this.OrderValueOfWorkerResult = OrderValueOfWorkerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SalesReport", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SalesReportRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.DateTime orderDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.DateTime deliverDate;
        
        public SalesReportRequest()
        {
        }
        
        public SalesReportRequest(System.DateTime orderDate, System.DateTime deliverDate)
        {
            this.orderDate = orderDate;
            this.deliverDate = deliverDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SalesReportResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SalesReportResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Nullable<decimal> SalesReportResult;
        
        public SalesReportResponse()
        {
        }
        
        public SalesReportResponse(System.Nullable<decimal> SalesReportResult)
        {
            this.SalesReportResult = SalesReportResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IGameStoreServiceChannel : ServiceReferenceGameStore.IGameStoreService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class GameStoreServiceClient : System.ServiceModel.ClientBase<ServiceReferenceGameStore.IGameStoreService>, ServiceReferenceGameStore.IGameStoreService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public GameStoreServiceClient() : 
                base(GameStoreServiceClient.GetDefaultBinding(), GameStoreServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IGameStoreService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GameStoreServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(GameStoreServiceClient.GetBindingForEndpoint(endpointConfiguration), GameStoreServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GameStoreServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(GameStoreServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GameStoreServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(GameStoreServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GameStoreServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public ServiceReferenceGameStore.GetGamesResponse GetGames(ServiceReferenceGameStore.GetGamesRequest request)
        {
            return base.Channel.GetGames(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceGameStore.GetGamesResponse> GetGamesAsync(ServiceReferenceGameStore.GetGamesRequest request)
        {
            return base.Channel.GetGamesAsync(request);
        }
        
        public ServiceReferenceGameStore.GetGameSortByNameResponse GetGameSortByName(ServiceReferenceGameStore.GetGameSortByNameRequest request)
        {
            return base.Channel.GetGameSortByName(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceGameStore.GetGameSortByNameResponse> GetGameSortByNameAsync(ServiceReferenceGameStore.GetGameSortByNameRequest request)
        {
            return base.Channel.GetGameSortByNameAsync(request);
        }
        
        public ServiceReferenceGameStore.AddOrUpdateGameResponse AddOrUpdateGame(ServiceReferenceGameStore.AddOrUpdateGameRequest request)
        {
            return base.Channel.AddOrUpdateGame(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceGameStore.AddOrUpdateGameResponse> AddOrUpdateGameAsync(ServiceReferenceGameStore.AddOrUpdateGameRequest request)
        {
            return base.Channel.AddOrUpdateGameAsync(request);
        }
        
        public ServiceReferenceGameStore.GetCustomersResponse GetCustomers(ServiceReferenceGameStore.GetCustomersRequest request)
        {
            return base.Channel.GetCustomers(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceGameStore.GetCustomersResponse> GetCustomersAsync(ServiceReferenceGameStore.GetCustomersRequest request)
        {
            return base.Channel.GetCustomersAsync(request);
        }
        
        public ServiceReferenceGameStore.GetCustomerSortByNameResponse GetCustomerSortByName(ServiceReferenceGameStore.GetCustomerSortByNameRequest request)
        {
            return base.Channel.GetCustomerSortByName(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceGameStore.GetCustomerSortByNameResponse> GetCustomerSortByNameAsync(ServiceReferenceGameStore.GetCustomerSortByNameRequest request)
        {
            return base.Channel.GetCustomerSortByNameAsync(request);
        }
        
        public ServiceReferenceGameStore.AddOrUpdateCustomerResponse AddOrUpdateCustomer(ServiceReferenceGameStore.AddOrUpdateCustomerRequest request)
        {
            return base.Channel.AddOrUpdateCustomer(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceGameStore.AddOrUpdateCustomerResponse> AddOrUpdateCustomerAsync(ServiceReferenceGameStore.AddOrUpdateCustomerRequest request)
        {
            return base.Channel.AddOrUpdateCustomerAsync(request);
        }
        
        public ServiceReferenceGameStore.AddOrUpdateEmployeeResponse AddOrUpdateEmployee(ServiceReferenceGameStore.AddOrUpdateEmployeeRequest request)
        {
            return base.Channel.AddOrUpdateEmployee(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceGameStore.AddOrUpdateEmployeeResponse> AddOrUpdateEmployeeAsync(ServiceReferenceGameStore.AddOrUpdateEmployeeRequest request)
        {
            return base.Channel.AddOrUpdateEmployeeAsync(request);
        }
        
        public ServiceReferenceGameStore.GetEmployeesResponse GetEmployees(ServiceReferenceGameStore.GetEmployeesRequest request)
        {
            return base.Channel.GetEmployees(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceGameStore.GetEmployeesResponse> GetEmployeesAsync(ServiceReferenceGameStore.GetEmployeesRequest request)
        {
            return base.Channel.GetEmployeesAsync(request);
        }
        
        public ServiceReferenceGameStore.GetEmployeeSortByNameResponse GetEmployeeSortByName(ServiceReferenceGameStore.GetEmployeeSortByNameRequest request)
        {
            return base.Channel.GetEmployeeSortByName(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceGameStore.GetEmployeeSortByNameResponse> GetEmployeeSortByNameAsync(ServiceReferenceGameStore.GetEmployeeSortByNameRequest request)
        {
            return base.Channel.GetEmployeeSortByNameAsync(request);
        }
        
        public ServiceReferenceGameStore.GetOrdersResponse GetOrders(ServiceReferenceGameStore.GetOrdersRequest request)
        {
            return base.Channel.GetOrders(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceGameStore.GetOrdersResponse> GetOrdersAsync(ServiceReferenceGameStore.GetOrdersRequest request)
        {
            return base.Channel.GetOrdersAsync(request);
        }
        
        public ServiceReferenceGameStore.GetOrderSortByOrderNumberResponse GetOrderSortByOrderNumber(ServiceReferenceGameStore.GetOrderSortByOrderNumberRequest request)
        {
            return base.Channel.GetOrderSortByOrderNumber(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceGameStore.GetOrderSortByOrderNumberResponse> GetOrderSortByOrderNumberAsync(ServiceReferenceGameStore.GetOrderSortByOrderNumberRequest request)
        {
            return base.Channel.GetOrderSortByOrderNumberAsync(request);
        }
        
        public ServiceReferenceGameStore.AddOrUpdateOrderResponse AddOrUpdateOrder(ServiceReferenceGameStore.AddOrUpdateOrderRequest request)
        {
            return base.Channel.AddOrUpdateOrder(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceGameStore.AddOrUpdateOrderResponse> AddOrUpdateOrderAsync(ServiceReferenceGameStore.AddOrUpdateOrderRequest request)
        {
            return base.Channel.AddOrUpdateOrderAsync(request);
        }
        
        public ServiceReferenceGameStore.GetCategoriesResponse GetCategories(ServiceReferenceGameStore.GetCategoriesRequest request)
        {
            return base.Channel.GetCategories(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceGameStore.GetCategoriesResponse> GetCategoriesAsync(ServiceReferenceGameStore.GetCategoriesRequest request)
        {
            return base.Channel.GetCategoriesAsync(request);
        }
        
        public ServiceReferenceGameStore.GetCategorySortByNameResponse GetCategorySortByName(ServiceReferenceGameStore.GetCategorySortByNameRequest request)
        {
            return base.Channel.GetCategorySortByName(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceGameStore.GetCategorySortByNameResponse> GetCategorySortByNameAsync(ServiceReferenceGameStore.GetCategorySortByNameRequest request)
        {
            return base.Channel.GetCategorySortByNameAsync(request);
        }
        
        public ServiceReferenceGameStore.AddOrUpdateCategoryResponse AddOrUpdateCategory(ServiceReferenceGameStore.AddOrUpdateCategoryRequest request)
        {
            return base.Channel.AddOrUpdateCategory(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceGameStore.AddOrUpdateCategoryResponse> AddOrUpdateCategoryAsync(ServiceReferenceGameStore.AddOrUpdateCategoryRequest request)
        {
            return base.Channel.AddOrUpdateCategoryAsync(request);
        }
        
        public ServiceReferenceGameStore.GetGameTypesResponse GetGameTypes(ServiceReferenceGameStore.GetGameTypesRequest request)
        {
            return base.Channel.GetGameTypes(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceGameStore.GetGameTypesResponse> GetGameTypesAsync(ServiceReferenceGameStore.GetGameTypesRequest request)
        {
            return base.Channel.GetGameTypesAsync(request);
        }
        
        public ServiceReferenceGameStore.AddOrUpdateGameTypeResponse AddOrUpdateGameType(ServiceReferenceGameStore.AddOrUpdateGameTypeRequest request)
        {
            return base.Channel.AddOrUpdateGameType(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceGameStore.AddOrUpdateGameTypeResponse> AddOrUpdateGameTypeAsync(ServiceReferenceGameStore.AddOrUpdateGameTypeRequest request)
        {
            return base.Channel.AddOrUpdateGameTypeAsync(request);
        }
        
        public ServiceReferenceGameStore.GetPaymentMethodsResponse GetPaymentMethods(ServiceReferenceGameStore.GetPaymentMethodsRequest request)
        {
            return base.Channel.GetPaymentMethods(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceGameStore.GetPaymentMethodsResponse> GetPaymentMethodsAsync(ServiceReferenceGameStore.GetPaymentMethodsRequest request)
        {
            return base.Channel.GetPaymentMethodsAsync(request);
        }
        
        public ServiceReferenceGameStore.AddOrUpdatePaymentMethodResponse AddOrUpdatePaymentMethod(ServiceReferenceGameStore.AddOrUpdatePaymentMethodRequest request)
        {
            return base.Channel.AddOrUpdatePaymentMethod(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceGameStore.AddOrUpdatePaymentMethodResponse> AddOrUpdatePaymentMethodAsync(ServiceReferenceGameStore.AddOrUpdatePaymentMethodRequest request)
        {
            return base.Channel.AddOrUpdatePaymentMethodAsync(request);
        }
        
        public ServiceReferenceGameStore.GetOrderDetailResponse GetOrderDetail(ServiceReferenceGameStore.GetOrderDetailRequest request)
        {
            return base.Channel.GetOrderDetail(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceGameStore.GetOrderDetailResponse> GetOrderDetailAsync(ServiceReferenceGameStore.GetOrderDetailRequest request)
        {
            return base.Channel.GetOrderDetailAsync(request);
        }
        
        public ServiceReferenceGameStore.SalesReportForGameResponse SalesReportForGame(ServiceReferenceGameStore.SalesReportForGameRequest request)
        {
            return base.Channel.SalesReportForGame(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceGameStore.SalesReportForGameResponse> SalesReportForGameAsync(ServiceReferenceGameStore.SalesReportForGameRequest request)
        {
            return base.Channel.SalesReportForGameAsync(request);
        }
        
        public ServiceReferenceGameStore.OrderValueOfWorkerResponse OrderValueOfWorker(ServiceReferenceGameStore.OrderValueOfWorkerRequest request)
        {
            return base.Channel.OrderValueOfWorker(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceGameStore.OrderValueOfWorkerResponse> OrderValueOfWorkerAsync(ServiceReferenceGameStore.OrderValueOfWorkerRequest request)
        {
            return base.Channel.OrderValueOfWorkerAsync(request);
        }
        
        public ServiceReferenceGameStore.SalesReportResponse SalesReport(ServiceReferenceGameStore.SalesReportRequest request)
        {
            return base.Channel.SalesReport(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceGameStore.SalesReportResponse> SalesReportAsync(ServiceReferenceGameStore.SalesReportRequest request)
        {
            return base.Channel.SalesReportAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IGameStoreService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IGameStoreService))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.1.178:64946/GameStoreService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return GameStoreServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IGameStoreService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return GameStoreServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IGameStoreService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IGameStoreService,
        }
    }
}
